version: '3.8'

services:
  # PostgreSQL 資料庫服務
  postgres:
    image: postgres:16-alpine
    container_name: meethalf-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=meethalf
      - POSTGRES_PASSWORD=meethalf_password
      - POSTGRES_DB=meethalf
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      # 持久化資料庫資料
      - postgres-data:/var/lib/postgresql/data
    networks:
      - meethalf-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meethalf"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin (可選，用於資料庫管理)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: meethalf-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@meethalf.local
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - meethalf-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  # 後端服務 (Express + Prisma + PostgreSQL)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: meethalf-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://meethalf:meethalf_password@postgres:5432/meethalf
      - JWT_SECRET=${JWT_SECRET:-your_super_secret_jwt_key_min_32_chars_please_change_this}
      - FRONTEND_ORIGIN=http://localhost:5173
      - GOOGLE_MAPS_SERVER_KEY=${GOOGLE_MAPS_SERVER_KEY}
    volumes:
      # 可選：掛載環境變數檔案
      - ./backend/.env:/app/.env:ro
    networks:
      - meethalf-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 前端服務 (Vite + React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: meethalf-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3000
      - VITE_GOOGLE_MAPS_JS_KEY=${VITE_GOOGLE_MAPS_JS_KEY}
    volumes:
      # 開發模式：掛載原始碼以支援熱重載
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      # 可選：掛載環境變數檔案
      - ./frontend/.env:/app/.env:ro
    networks:
      - meethalf-network
    restart: unless-stopped
    depends_on:
      - backend

networks:
  meethalf-network:
    driver: bridge

volumes:
  # PostgreSQL 資料持久化
  postgres-data:
    driver: local
  # pgAdmin 資料持久化
  pgadmin-data:
    driver: local
