steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/treasure-map-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/treasure-map-backend:latest'
      - '.'
    dir: 'hw4/backend'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/treasure-map-backend'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'treasure-map-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/treasure-map-backend:$SHORT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-east1'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--port'
      - '8000'

# Substitutions for dynamic values
substitutions:
  _SERVICE_NAME: treasure-map-backend
  _REGION: asia-east1

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '1200s'

# Images to be pushed to the registry
images:
  - 'gcr.io/$PROJECT_ID/treasure-map-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/treasure-map-backend:latest'
